modLoader="javafml"
loaderVersion="[32,)"
license="LGPL v3"
issueTrackerURL="https://github.com/OwendB1/InfinityCrossbow/issues"

[[mods]]
modId="infinitycrossbow"
version="${file.jarVersion}"
displayName="InfinityCrossbow"
displayURL="https://www.curseforge.com/minecraft/mc-mods/infinitycrossbow-forge"
credits="Thanks to traverse_joe for the idea and Keksuccino for teaching me the coremodding basics"
authors="OwendB"
description="Allows you to enchant the crossbow with the Infinity enchant and removes the need to have an arrow in your inventory when the enchant is applied."

[[dependencies.infinitycrossbow]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinitycrossbow]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.16.5)"
    ordering="NONE"
    side="BOTH"